define(["jade"],function(jade){

return function template(locals) {
var buf = [];
var jade_mixins = {};
var jade_interp;

buf.push("<div tabs=\"tabs\"><div id=\"file\" data-js=\"dropdown\" class=\"dropdown pull-left\"><div id=\"fileLabel\" tab=\"fileMenu\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">ファイル</div><ul data-js=\"fileMenu\" menuList=\"file\" class=\"dropdown-menu\"><li data-js=\"openModal\" fileMenu=\"newFile\" modalClass=\"#fileModal\">新規ファイル</li><div data-js=\"newCanvas\"><div id=\"fileModal\" data-js=\"fileModal\" class=\"modal fade\"><div class=\"modal-dialog\"><div class=\"modal-content\"><div class=\"modal-header\"><h4 id=\"fileModalLabel\" class=\"modal-title\">新規キャンバス</h4></div><div class=\"modal-body\"><div for=\"canvasName\" class=\"label\">名前：</div><input id=\"canvasName\" data-js=\"canvasName\" sclass=\"form-control\" name=\"canvasName\" type=\"text\" value=\"新規キャンバス\"/></div><div [clear]=\"[clear]\"></div><div class=\"modal-footer\"><button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-default\">キャンセル</button><button type=\"submit\" data-js=\"submit\" class=\"btn btn-primary\">ＯＫ</button></div></div></div></div></div></ul></div><div id=\"window\" data-js=\"dropdown\" class=\"dropdown pull-left\"><div id=\"windowLabel\" tab=\"windowMenu\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">ウインドウ</div><ul data-js=\"windowMenu\" menuList=\"file\" role=\"menu\" aria-labelledby=\"windowLabel\" class=\"dropdown-menu\"><li data-js=\"showTool\" windowMenu=\"tool\">ツール</li></ul></div><div id=\"share\" data-js=\"dropdown\" class=\"dropdown pull-left\"><div id=\"showLabel\" tab=\"shareMenu\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">シェア</div><ul data-js=\"shareMenu\" menuList=\"file\" role=\"menu\" aria-labelledby=\"shareLabel\" class=\"dropdown-menu\"><li shareMenu=\"facebook\"><a share-Wrap=\"share-Wrap\" href=\"http://www.facebook.com/share.php?u=https://gamerinshaft.azurewebsites.net/thumix\" onclick=\"window.open(this.href, 'FBwindow', 'width=650, height=450, menubar=no, toolbar=no, scrollbars=yes'); return false;\">Facebook</a></li><li shareMenu=\"twitter\"><a share-Wrap=\"share-Wrap\" href=\"http://twitter.com/share?count=horizontal&amp;amp;original_referer=http://gamerinshaft.azurewebsites.net/thumix&amp;amp;text=Web上で簡単に画像合成できるサービスなんじゃ＾〜 &amp;amp;url=http://gamerinshaft.azurewebsites.net/thumix\" onclick=\"window.open(this.href, 'tweetwindow', 'width=550, height=450,personalbar=0,toolbar=0,scrollbars=1,resizable=1'); return false;\">Twitter</a></li></ul></div><div clear=\"clear\"></div></div>");;return buf.join("");
};

});
